name: Publish Python distributions to PyPI and TestPyPI
env:
  BOOST_PYTHON_LIB: boost_python
  BOOST_SYSTEM_LIB: boost_system
  BOOST_THREAD_LIB: boost_thread
  PYCAIRO: true
  MASON_BUILD: true
on: [push, pull_request]
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "2.7"
        #- "3.6"
        #- "3.8"
        system:
        #- ubuntu-18.04
        - ubuntu-20.04
    runs-on: ${{matrix.system}}
    name: Build and publish Python distribution
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: install dependencies
        run: |
          sudo apt-get install libboost-python-dev python3-cairo-dev python-cairo-dev clang
      #clang-3.9
      - name: Initialize Python {{matrix.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build binary wheel and a source tarball
        run: |
          pip install wheel pycairo
          python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
      - name: Run tests
        run: |
          source mason-config.env
          /mason_packages/.link/bin/postgres -k ${PGHOST} > postgres.log &
          python test/run_tests.py
          python test/visual.py -q
          ./mason_packages/.link/bin/pg_ctl -w stop
